-- ============================================
-- SCRIPT PARA APLICAR TODAS AS MIGRATIONS
-- Execute este SQL no Supabase Dashboard → SQL Editor
-- ============================================

-- 1. Criar tabela Profiles (se não existir)
CREATE TABLE IF NOT EXISTS "Profiles" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(200) NOT NULL,
    "Role" character varying(200) NOT NULL,
    "Location" character varying(100),
    "Languages" character varying(200),
    "Description" character varying(2000),
    "AvatarUrl" character varying(500),
    "ExperienceYears" character varying(50),
    "CoreEngine" character varying(200),
    "Database" character varying(200),
    "Email" character varying(200),
    "GitHubUrl" character varying(500),
    "LinkedInUrl" character varying(500),
    "Specialized" character varying(200),
    "Certifications" character varying(500),
    "AboutText" character varying(3000),
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
    "UpdatedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL DEFAULT false,
    CONSTRAINT "PK_Profiles" PRIMARY KEY ("Id")
);

-- 2. Adicionar coluna AboutText se não existir (para tabelas já criadas)
DO $$ 
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_name = 'Profiles' AND column_name = 'AboutText'
    ) THEN
        ALTER TABLE "Profiles" ADD COLUMN "AboutText" character varying(3000);
    END IF;
END $$;

-- 3. Garantir que Languages tenha tamanho correto (200)
ALTER TABLE "Profiles" 
ALTER COLUMN "Languages" TYPE character varying(200);

-- 4. Criar tabela de histórico de migrations (se não existir)
CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

-- 5. Registrar migrations aplicadas
INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES 
    ('20260202234831_InitialCreate', '8.0.11'),
    ('20260205171548_AddProfileEntity', '8.0.11'),
    ('20260205180000_IncreaseProfileLanguagesLength', '8.0.11'),
    ('20260205190000_AddAboutTextToProfile', '8.0.11')
ON CONFLICT ("MigrationId") DO NOTHING;

-- Verificar se as tabelas existem
SELECT 
    table_name,
    column_name,
    data_type,
    character_maximum_length
FROM information_schema.columns
WHERE table_name IN ('Profiles', 'Projects', 'Skills', 'Experiences')
ORDER BY table_name, ordinal_position;
