-- Conteúdo do heliofilho.dev: cofre, projetos e diário dos projetos.
-- Gerado por scripts/content-sql.mjs. Rodar no SQL Editor do Supabase (projeto do portfólio).

create table if not exists cofre_items (
  slug text primary key check (slug ~ '^[a-z0-9-]+$'),
  category text not null check (category in ('Vídeos', 'Repos', 'Produtos', 'Livros', 'Guias')),
  topic text,
  title text not null,
  summary text not null,
  body_md text not null default '',
  tone text not null default 'lilac' check (tone in ('lilac', 'mint', 'peach', 'butter', 'sky', 'rose')),
  video_url text,
  keyword text,
  materials jsonb not null default '[]',
  chapters jsonb not null default '[]',
  published boolean not null default true,
  published_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create unique index if not exists cofre_items_keyword on cofre_items (upper(keyword)) where keyword is not null;

create table if not exists site_projects (
  slug text primary key check (slug ~ '^[a-z0-9-]+$'),
  name text not null,
  type text not null,
  status text not null check (status in ('No ar', 'Em construção', 'Ideia')),
  year text,
  stack text not null default '',
  summary text not null,
  url text,
  repo_url text,
  tone text not null default 'lilac' check (tone in ('lilac', 'mint', 'peach', 'butter', 'sky', 'rose')),
  problem text,
  solution text,
  arch text[] not null default '{}',
  decisions text[] not null default '{}',
  tradeoffs text[] not null default '{}',
  readme_md text not null default '',
  sort int not null default 0,
  published boolean not null default true
);

create table if not exists project_updates (
  id bigint generated by default as identity primary key,
  project_slug text not null references site_projects (slug) on update cascade on delete cascade,
  title text not null,
  body_md text not null,
  published_at timestamptz not null default now()
);

alter table cofre_items enable row level security;
alter table site_projects enable row level security;
alter table project_updates enable row level security;

drop policy if exists "cofre publico" on cofre_items;
create policy "cofre publico" on cofre_items for select using (published);
drop policy if exists "projetos publicos" on site_projects;
create policy "projetos publicos" on site_projects for select using (published);
drop policy if exists "diario publico" on project_updates;
create policy "diario publico" on project_updates for select using (true);

insert into cofre_items (slug, category, topic, title, summary, body_md, tone, video_url, keyword, materials, chapters, published_at)
values ('repositorios-secretos', 'Vídeos', null, 'Central de Repositórios Secretos', 'Alguns dos projetos mais curiosos que encontrei no GitHub.', 'Tecnologia, IA, internet e as coisas mais estranhas que encontro pelo caminho.

> **Atenção:** verifique sempre a licença, segurança e finalidade de cada projeto antes de instalar qualquer software.

## Streaming e TV

### SmartTube
**GitHub:** [yuliskov/SmartTube](https://github.com/yuliskov/SmartTube)

Cliente gratuito e open source para **Android TV e TV boxes**, com recursos como SponsorBlock, reprodução em 8K/60fps, HDR e interface otimizada para televisão. O projeto informa que não é oficialmente distribuído por lojas de aplicativos e recomenda utilizar seus canais oficiais de instalação.

**Compatibilidade:** Android TV e TV boxes.
**Não funciona:** iPhone, Apple TV, Samsung Tizen e LG webOS.

> ⚠️ Baixe somente pelos canais indicados no próprio projeto. O mantenedor alerta sobre cópias distribuídas por sites de APK e terceiros.

### Sonarr
**GitHub:** [stevietv/Sonarr](https://github.com/stevietv/Sonarr)

Ferramenta de gerenciamento automatizado de séries e conteúdo de mídia. O repositório apresentado é voltado a automação de uma biblioteca de mídia.

> ⚠️ O projeto pode envolver automação de downloads. Use somente com conteúdo que você tenha direito de obter.

## Adobe e design

### GenP
**GitHub:** [TheMythologist/GenP](https://github.com/TheMythologist/GenP)

Projeto open source que automatiza a compilação do **GenP**, um patcher relacionado ao licenciamento dos aplicativos Adobe Creative Cloud. O próprio repositório diz que seu uso pode violar os termos da Adobe e leis aplicáveis.

**Importante:** não recomendo instalar ou utilizar ferramentas para contornar licenças. Se o objetivo for estudar o projeto, o código-fonte e a estrutura do repositório estão disponíveis publicamente.

## Projetos curiosos

### grqz/grqz
**GitHub:** [grqz/grqz](https://github.com/grqz/grqz)

Repositório pessoal do desenvolvedor **GRQZ**, apresentado como um espaço para experimentar diferentes projetos e ideias.

### WitherOrNot/llvm-project
**GitHub:** [WitherOrNot/llvm-project](https://github.com/WitherOrNot/llvm-project)

Fork/modificação do projeto LLVM, uma coleção de tecnologias de compiladores e ferramentas de desenvolvimento.

## Antes de instalar qualquer projeto

- Prefira sempre o **repositório original**.
- Leia o README e as instruções oficiais.
- Verifique a licença.
- Não execute arquivos `.exe`, scripts ou APKs de fontes desconhecidas.
- Não use ferramentas para contornar licenças ou acessar conteúdo sem autorização.
- Projetos no GitHub podem mudar de mantenedor ou ser comprometidos; verifique a atividade e os avisos recentes antes de executar qualquer coisa.', 'rose', null, 'REPOS', '[{"label":"SmartTube","sub":"GitHub · Android TV","url":"https://github.com/yuliskov/SmartTube"},{"label":"Sonarr","sub":"GitHub · mídia","url":"https://github.com/stevietv/Sonarr"},{"label":"GenP","sub":"GitHub · só para estudo","url":"https://github.com/TheMythologist/GenP"},{"label":"grqz/grqz","sub":"GitHub","url":"https://github.com/grqz/grqz"},{"label":"WitherOrNot/llvm-project","sub":"GitHub · compiladores","url":"https://github.com/WitherOrNot/llvm-project"}]'::jsonb, '[]'::jsonb, '2026-09-26T12:00:00Z')
on conflict (slug) do update set category = excluded.category, topic = excluded.topic, title = excluded.title, summary = excluded.summary,
  body_md = excluded.body_md, tone = excluded.tone, video_url = excluded.video_url, keyword = excluded.keyword,
  materials = excluded.materials, chapters = excluded.chapters, updated_at = now();

insert into cofre_items (slug, category, topic, title, summary, body_md, tone, video_url, keyword, materials, chapters, published_at)
values ('ollama', 'Repos', 'IA no seu computador', 'Ollama', 'Roda modelos de IA abertos no seu computador, com um comando só.', '## O que é

O Ollama é uma ferramenta que baixa e executa modelos de linguagem abertos, como Llama, Gemma, Mistral e Qwen, direto na sua máquina. Ele cuida da parte chata (download, configuração, uso da placa de vídeo) e você só conversa.

## Por que vale a pena

- **Privacidade:** nada sai do seu computador. Dá para usar com documentos sensíveis.
- **Custo zero por uso:** sem assinatura e sem limite de mensagens.
- **Funciona offline:** depois de baixar o modelo, não precisa de internet.
- **Para devs:** expõe uma API local, então dá para integrar IA nos seus projetos sem pagar API.

## Como começar

1. Baixe o instalador no site oficial do Ollama (Windows, Mac ou Linux).
2. Abra o terminal e rode `ollama run <nome do modelo>`. A lista de modelos fica na biblioteca do próprio Ollama.
3. Converse direto no terminal. Para uma interface bonita, use o Open WebUI junto.

## Pra quem é

Qualquer pessoa curiosa com IA. Modelos pequenos rodam bem até em notebook comum; os maiores pedem mais memória e uma boa placa de vídeo.

→ [Abrir no GitHub](https://github.com/ollama/ollama)', 'lilac', null, null, '[]'::jsonb, '[]'::jsonb, '2026-09-20T12:00:00Z')
on conflict (slug) do update set category = excluded.category, topic = excluded.topic, title = excluded.title, summary = excluded.summary,
  body_md = excluded.body_md, tone = excluded.tone, video_url = excluded.video_url, keyword = excluded.keyword,
  materials = excluded.materials, chapters = excluded.chapters, updated_at = now();

insert into cofre_items (slug, category, topic, title, summary, body_md, tone, video_url, keyword, materials, chapters, published_at)
values ('open-webui', 'Repos', 'IA no seu computador', 'Open WebUI', 'Uma interface parecida com o ChatGPT para os modelos que rodam no seu computador.', '## O que é

O Open WebUI é uma interface web open source para conversar com modelos de IA locais (via Ollama) ou por API. Ele transforma o terminal numa experiência de chat completa.

## Por que vale a pena

- Histórico de conversas, vários modelos e troca rápida entre eles.
- Upload de documentos para conversar com seus próprios arquivos.
- Contas de usuário: dá para compartilhar com a família ou a equipe.

## Como começar

1. Tenha o Ollama instalado e funcionando.
2. Suba o Open WebUI via Docker, usando o comando do README do projeto.
3. Abra no navegador, crie sua conta e escolha o modelo.

## Pra quem é

Quem já testou o Ollama e quer uma experiência de uso diário. Precisa de Docker instalado.

→ [Abrir no GitHub](https://github.com/open-webui/open-webui)', 'lilac', null, null, '[]'::jsonb, '[]'::jsonb, '2026-09-20T11:00:00Z')
on conflict (slug) do update set category = excluded.category, topic = excluded.topic, title = excluded.title, summary = excluded.summary,
  body_md = excluded.body_md, tone = excluded.tone, video_url = excluded.video_url, keyword = excluded.keyword,
  materials = excluded.materials, chapters = excluded.chapters, updated_at = now();

insert into cofre_items (slug, category, topic, title, summary, body_md, tone, video_url, keyword, materials, chapters, published_at)
values ('jellyfin', 'Repos', 'Mídia e streaming', 'Jellyfin', 'Seu próprio servidor de streaming, com os seus filmes, séries e músicas.', '## O que é

O Jellyfin é um servidor de mídia open source. Você aponta para as pastas com seus arquivos e ele organiza tudo com capas, sinopses e "continuar assistindo", como um serviço de streaming, só que seu.

## Por que vale a pena

- **100% gratuito:** sem assinatura e sem recursos travados atrás de plano pago.
- **Assiste em qualquer lugar:** navegador, celular, smart TV e videogame.
- **Seus arquivos, suas regras:** sem anúncio e sem coleta de dados.

## Como começar

1. Instale o Jellyfin num computador que fica ligado (ou via Docker).
2. Abra no navegador e adicione as pastas da sua biblioteca.
3. Instale o app do Jellyfin na TV ou no celular e conecte ao seu servidor.

## Pra quem é

Quem tem uma coleção própria de filmes, séries, músicas ou vídeos de família e quer assistir de qualquer aparelho da casa.

→ [Abrir no GitHub](https://github.com/jellyfin/jellyfin)', 'peach', null, null, '[]'::jsonb, '[]'::jsonb, '2026-09-19T12:00:00Z')
on conflict (slug) do update set category = excluded.category, topic = excluded.topic, title = excluded.title, summary = excluded.summary,
  body_md = excluded.body_md, tone = excluded.tone, video_url = excluded.video_url, keyword = excluded.keyword,
  materials = excluded.materials, chapters = excluded.chapters, updated_at = now();

insert into cofre_items (slug, category, topic, title, summary, body_md, tone, video_url, keyword, materials, chapters, published_at)
values ('yt-dlp', 'Repos', 'Mídia e streaming', 'yt-dlp', 'Baixa vídeo e áudio de milhares de sites, com controle total de qualidade e formato.', '## O que é

O yt-dlp é um programa de linha de comando open source para baixar vídeos e áudios. É o sucessor mais ativo do antigo youtube-dl e suporta milhares de sites.

## Por que vale a pena

- Sem anúncio, sem site duvidoso e sem limite de download.
- Escolhe resolução, extrai só o áudio, baixa playlists inteiras e legendas.
- Atualizado com frequência pela comunidade.

## Como começar

1. Instale pelo gerenciador de pacotes do seu sistema (winget, brew ou pip).
2. No terminal, rode `yt-dlp <link do vídeo>`.
3. Para baixar só o áudio: `yt-dlp -x <link>`.

## Pra quem é

Quem não tem medo de terminal. Use com responsabilidade: baixe apenas conteúdo que você tem direito de guardar.

→ [Abrir no GitHub](https://github.com/yt-dlp/yt-dlp)', 'peach', null, null, '[]'::jsonb, '[]'::jsonb, '2026-09-19T11:00:00Z')
on conflict (slug) do update set category = excluded.category, topic = excluded.topic, title = excluded.title, summary = excluded.summary,
  body_md = excluded.body_md, tone = excluded.tone, video_url = excluded.video_url, keyword = excluded.keyword,
  materials = excluded.materials, chapters = excluded.chapters, updated_at = now();

insert into cofre_items (slug, category, topic, title, summary, body_md, tone, video_url, keyword, materials, chapters, published_at)
values ('immich', 'Repos', 'Troque serviços pagos', 'Immich', 'Uma alternativa ao Google Fotos que roda no seu próprio servidor.', '## O que é

O Immich é um sistema open source de fotos e vídeos com app para celular, backup automático, reconhecimento facial, mapa de lugares e busca inteligente ("praia", "cachorro", "aniversário").

## Por que vale a pena

- Para de pagar armazenamento na nuvem todo mês.
- Suas fotos ficam sob seu controle, e não no servidor de uma empresa.
- A experiência é muito parecida com a do Google Fotos.

## Como começar

1. Separe um computador ou servidor que fique sempre ligado, com espaço em disco.
2. Instale via Docker Compose seguindo o guia oficial.
3. Instale o app Immich no celular, aponte para o seu servidor e ative o backup.

## Pra quem é

Quem tem milhares de fotos e quer sair da mensalidade. Exige um pouco de configuração e um disco confiável (faça backup do backup).

→ [Abrir no GitHub](https://github.com/immich-app/immich)', 'mint', null, null, '[]'::jsonb, '[]'::jsonb, '2026-09-18T12:00:00Z')
on conflict (slug) do update set category = excluded.category, topic = excluded.topic, title = excluded.title, summary = excluded.summary,
  body_md = excluded.body_md, tone = excluded.tone, video_url = excluded.video_url, keyword = excluded.keyword,
  materials = excluded.materials, chapters = excluded.chapters, updated_at = now();

insert into cofre_items (slug, category, topic, title, summary, body_md, tone, video_url, keyword, materials, chapters, published_at)
values ('n8n', 'Repos', 'Troque serviços pagos', 'n8n', 'Automação visual estilo Zapier que você pode hospedar sozinho, com IA integrada.', '## O que é

O n8n é uma plataforma de automação: você conecta apps, APIs e modelos de IA arrastando blocos, e ainda pode escrever código quando precisar.

## Por que vale a pena

- Hospedando você mesmo, não paga por execução.
- Centenas de integrações prontas (planilhas, e-mail, Telegram, Notion, IA).
- Automatiza desde relatórios até resumos diários feitos com IA.

## Como começar

1. Para testar rápido, rode `npx n8n` ou suba via Docker.
2. Abra no navegador e crie seu primeiro fluxo a partir de um template.
3. Quando gostar, hospede num servidor para rodar 24 horas.

## Pra quem é

Quem repete tarefas no computador toda semana. Existe também uma versão em nuvem, paga, para quem não quer manter servidor.

→ [Abrir no GitHub](https://github.com/n8n-io/n8n)', 'mint', null, null, '[]'::jsonb, '[]'::jsonb, '2026-09-18T11:00:00Z')
on conflict (slug) do update set category = excluded.category, topic = excluded.topic, title = excluded.title, summary = excluded.summary,
  body_md = excluded.body_md, tone = excluded.tone, video_url = excluded.video_url, keyword = excluded.keyword,
  materials = excluded.materials, chapters = excluded.chapters, updated_at = now();

insert into cofre_items (slug, category, topic, title, summary, body_md, tone, video_url, keyword, materials, chapters, published_at)
values ('localsend', 'Repos', 'Ferramentas do dia a dia', 'LocalSend', 'Um AirDrop que funciona entre qualquer sistema: Windows, Mac, Linux, Android e iPhone.', '## O que é

O LocalSend é um app open source para enviar arquivos entre aparelhos na mesma rede Wi-Fi, sem internet, sem cadastro e sem nuvem no meio.

## Por que vale a pena

- Acabou o "manda no WhatsApp pra mim mesmo".
- Arquivos grandes vão direto de um aparelho para o outro, sem perder qualidade.
- Tudo criptografado e sem conta.

## Como começar

1. Instale o LocalSend nos dois aparelhos (tem nas lojas oficiais de todos os sistemas).
2. Conecte os dois na mesma rede Wi-Fi.
3. Escolha o arquivo, toque no aparelho de destino e aceite do outro lado.

## Pra quem é

Todo mundo. É o tipo de app que você instala uma vez e usa para sempre.

→ [Abrir no GitHub](https://github.com/localsend/localsend)', 'sky', null, null, '[]'::jsonb, '[]'::jsonb, '2026-09-17T12:00:00Z')
on conflict (slug) do update set category = excluded.category, topic = excluded.topic, title = excluded.title, summary = excluded.summary,
  body_md = excluded.body_md, tone = excluded.tone, video_url = excluded.video_url, keyword = excluded.keyword,
  materials = excluded.materials, chapters = excluded.chapters, updated_at = now();

insert into cofre_items (slug, category, topic, title, summary, body_md, tone, video_url, keyword, materials, chapters, published_at)
values ('stirling-pdf', 'Repos', 'Ferramentas do dia a dia', 'Stirling-PDF', 'Junta, divide, comprime, converte e edita PDF sem subir seus arquivos para site nenhum.', '## O que é

O Stirling-PDF é uma ferramenta open source com dezenas de funções para PDF, que roda na sua máquina ou no seu servidor, acessada pelo navegador.

## Por que vale a pena

- Substitui aqueles sites de PDF cheios de anúncio.
- Seus documentos não saem do seu computador: ideal para contrato, extrato e documento pessoal.
- Faz coisas que muita ferramenta paga cobra, como OCR, assinatura e compressão.

## Como começar

1. Instale via Docker ou pelo instalador desktop disponível no repositório.
2. Abra no navegador.
3. Escolha a ferramenta, arraste o PDF e baixe o resultado.

## Pra quem é

Quem mexe com PDF toda semana e se preocupa com privacidade.

→ [Abrir no GitHub](https://github.com/Stirling-Tools/Stirling-PDF)', 'sky', null, null, '[]'::jsonb, '[]'::jsonb, '2026-09-17T11:00:00Z')
on conflict (slug) do update set category = excluded.category, topic = excluded.topic, title = excluded.title, summary = excluded.summary,
  body_md = excluded.body_md, tone = excluded.tone, video_url = excluded.video_url, keyword = excluded.keyword,
  materials = excluded.materials, chapters = excluded.chapters, updated_at = now();

insert into cofre_items (slug, category, topic, title, summary, body_md, tone, video_url, keyword, materials, chapters, published_at)
values ('public-apis', 'Repos', 'Listas que valem ouro', 'Public APIs', 'Centenas de APIs gratuitas organizadas por tema, prontas para virar projeto.', '## O que é

Um dos repositórios mais famosos do GitHub: uma lista de APIs públicas separadas por categoria, como clima, finanças, filmes, games, música, esportes e muito mais.

## Por que vale a pena

- É o melhor remédio para o "não sei que projeto fazer".
- Cada API indica se precisa de chave, se aceita HTTPS e se funciona no navegador.
- Ótimo para montar portfólio com projetos que usam dados reais.

## Como começar

1. Abra o repositório e escolha uma categoria que te interessa.
2. Entre na documentação de uma API e faça sua primeira requisição.
3. Transforme em algo pequeno: um bot, um painel ou um app.

## Pra quem é

Quem está aprendendo a programar ou quer ideias de projeto.

→ [Abrir no GitHub](https://github.com/public-apis/public-apis)', 'butter', null, null, '[]'::jsonb, '[]'::jsonb, '2026-09-16T12:00:00Z')
on conflict (slug) do update set category = excluded.category, topic = excluded.topic, title = excluded.title, summary = excluded.summary,
  body_md = excluded.body_md, tone = excluded.tone, video_url = excluded.video_url, keyword = excluded.keyword,
  materials = excluded.materials, chapters = excluded.chapters, updated_at = now();

insert into cofre_items (slug, category, topic, title, summary, body_md, tone, video_url, keyword, materials, chapters, published_at)
values ('free-for-dev', 'Repos', 'Listas que valem ouro', 'free-for.dev', 'Todos os serviços com plano gratuito para quem desenvolve.', '## O que é

Uma lista mantida pela comunidade com serviços de hospedagem, banco de dados, autenticação, e-mail, monitoramento e muito mais que têm plano gratuito útil para desenvolvedores.

## Por que vale a pena

- Dá para colocar um projeto inteiro no ar gastando zero.
- Economiza horas de pesquisa comparando serviços.
- Perfeito para validar uma ideia de SaaS antes de gastar dinheiro.

## Como começar

1. Use o Ctrl+F para ir direto à categoria que você precisa.
2. Compare os limites de cada plano gratuito.
3. Sempre confira a página oficial do serviço, porque planos gratuitos mudam.

## Pra quem é

Devs com projeto pessoal, estudantes e quem está começando um SaaS.

→ [Abrir no GitHub](https://github.com/ripienaar/free-for-dev)', 'butter', null, null, '[]'::jsonb, '[]'::jsonb, '2026-09-16T11:00:00Z')
on conflict (slug) do update set category = excluded.category, topic = excluded.topic, title = excluded.title, summary = excluded.summary,
  body_md = excluded.body_md, tone = excluded.tone, video_url = excluded.video_url, keyword = excluded.keyword,
  materials = excluded.materials, chapters = excluded.chapters, updated_at = now();

insert into cofre_items (slug, category, topic, title, summary, body_md, tone, video_url, keyword, materials, chapters, published_at)
values ('book-of-secret-knowledge', 'Repos', 'Listas que valem ouro', 'The Book of Secret Knowledge', 'Um baú de ferramentas, comandos e truques de terminal, redes e segurança.', '## O que é

Uma coleção enorme de listas, manuais, cheatsheets, one-liners e ferramentas usadas por administradores de sistema, devs e profissionais de segurança.

## Por que vale a pena

- Comandos de terminal que economizam horas.
- Ferramentas de rede e segurança que pouca gente conhece.
- É o tipo de repositório que você salva e consulta por anos.

## Como começar

1. Não tente ler tudo: é grande demais.
2. Use o Ctrl+F com o assunto do momento: SSH, DNS, Docker, terminal.
3. Teste um comando novo por semana.

## Pra quem é

Devs, pessoas de infraestrutura e curiosos de segurança.

→ [Abrir no GitHub](https://github.com/trimstray/the-book-of-secret-knowledge)', 'butter', null, null, '[]'::jsonb, '[]'::jsonb, '2026-09-16T10:00:00Z')
on conflict (slug) do update set category = excluded.category, topic = excluded.topic, title = excluded.title, summary = excluded.summary,
  body_md = excluded.body_md, tone = excluded.tone, video_url = excluded.video_url, keyword = excluded.keyword,
  materials = excluded.materials, chapters = excluded.chapters, updated_at = now();

insert into cofre_items (slug, category, topic, title, summary, body_md, tone, video_url, keyword, materials, chapters, published_at)
values ('build-your-own-x', 'Repos', 'Aprender construindo', 'Build Your Own X', 'Tutoriais para recriar do zero as tecnologias que você usa todo dia.', '## O que é

Uma coleção de guias passo a passo para construir sua própria versão de Git, banco de dados, servidor web, navegador, blockchain e até sistema operacional, em várias linguagens.

## Por que vale a pena

- A melhor forma de entender algo é construir.
- Você sai de usuário para quem sabe o que acontece por baixo.
- Projetos assim chamam muita atenção no portfólio.

## Como começar

1. Escolha uma tecnologia que te dá curiosidade.
2. Filtre por uma linguagem que você já conhece.
3. Comece pelos menores, como um servidor web ou um interpretador simples.

## Pra quem é

Quem já programa o básico e quer subir de nível.

→ [Abrir no GitHub](https://github.com/codecrafters-io/build-your-own-x)', 'rose', null, null, '[]'::jsonb, '[]'::jsonb, '2026-09-15T12:00:00Z')
on conflict (slug) do update set category = excluded.category, topic = excluded.topic, title = excluded.title, summary = excluded.summary,
  body_md = excluded.body_md, tone = excluded.tone, video_url = excluded.video_url, keyword = excluded.keyword,
  materials = excluded.materials, chapters = excluded.chapters, updated_at = now();

insert into cofre_items (slug, category, topic, title, summary, body_md, tone, video_url, keyword, materials, chapters, published_at)
values ('developer-roadmap', 'Repos', 'Aprender construindo', 'Developer Roadmap', 'Mapas visuais do que estudar em cada carreira de tecnologia.', '## O que é

O projeto por trás do [roadmap.sh](https://roadmap.sh): trilhas interativas para frontend, backend, DevOps, IA, dados e dezenas de outras áreas e linguagens.

## Por que vale a pena

- Resolve a pergunta "o que eu estudo agora?".
- Você enxerga o caminho inteiro e marca o que já aprendeu.
- Cada tópico traz links de estudo gratuitos.

## Como começar

1. Acesse o site [roadmap.sh](https://roadmap.sh).
2. Escolha a trilha da carreira que você quer.
3. Siga os tópicos em ordem e marque seu progresso.

## Pra quem é

Quem está entrando na área, mudando de carreira ou quer tapar buracos no conhecimento.

→ [Abrir no GitHub](https://github.com/kamranahmedse/developer-roadmap)', 'rose', null, null, '[]'::jsonb, '[]'::jsonb, '2026-09-15T11:00:00Z')
on conflict (slug) do update set category = excluded.category, topic = excluded.topic, title = excluded.title, summary = excluded.summary,
  body_md = excluded.body_md, tone = excluded.tone, video_url = excluded.video_url, keyword = excluded.keyword,
  materials = excluded.materials, chapters = excluded.chapters, updated_at = now();

insert into cofre_items (slug, category, topic, title, summary, body_md, tone, video_url, keyword, materials, chapters, published_at)
values ('produtos-que-eu-uso', 'Produtos', null, 'Produtos que eu uso', 'O equipamento que eu uso para gravar meus vídeos. Se não uso, não entra aqui.', '*Como associado da Amazon, recebo por compras qualificadas, sem custo extra para você.*

## Áudio

### Shure SM7B
Microfone dinâmico de estúdio, o clássico de podcast. Por ser dinâmico, capta a voz e rejeita boa parte do ruído do ambiente, ótimo para quarto sem tratamento acústico.

→ [Ver na Amazon](https://link.amazon/B05DKW5Az)

### Hollyland Lark M2
Microfone de lapela sem fio, pequeno e discreto, com cancelamento de ruído e bateria para o dia todo. Liga direto no celular, perfeito para gravar em qualquer lugar.

→ [Ver na Amazon](https://link.amazon/B03btxoZr)

## Vídeo

### DJI Osmo Pocket 3
Câmera de bolso com estabilizador embutido, sensor de 1 polegada e gravação em 4K. Tela giratória para se enquadrar sozinho. Cabe no bolso e resolve quase toda gravação.

→ [Ver na Amazon](https://link.amazon/B03aah5Na)

## Periféricos

Em breve.', 'butter', null, 'SETUP', '[]'::jsonb, '[]'::jsonb, '2026-09-14T12:00:00Z')
on conflict (slug) do update set category = excluded.category, topic = excluded.topic, title = excluded.title, summary = excluded.summary,
  body_md = excluded.body_md, tone = excluded.tone, video_url = excluded.video_url, keyword = excluded.keyword,
  materials = excluded.materials, chapters = excluded.chapters, updated_at = now();

insert into cofre_items (slug, category, topic, title, summary, body_md, tone, video_url, keyword, materials, chapters, published_at)
values ('livros-que-recomendo', 'Livros', null, 'Livros que recomendo', 'Os livros que eu indicaria para quem programa ou quer programar, do primeiro passo até virar um dev melhor.', '*Como associado da Amazon, recebo por compras qualificadas, sem custo extra para você.*

## Fundamentos

### Aprendendo Git
*Anna Skoulikari*

Um guia prático e visual dos fundamentos do Git. Ideal para quem usa Git decorando comandos e quer finalmente entender o que está acontecendo.

→ [Ver na Amazon](https://link.amazon/B0fSnOB1w)

### Introdução à Linguagem SQL
*Thomas Nield*

Direto ao ponto para aprender a consultar e analisar dados com SQL. Uma das habilidades mais úteis para qualquer pessoa de tecnologia.

→ [Ver na Amazon](https://link.amazon/B0im2BWqX)

## Algoritmos e estruturas de dados

### Entendendo Algoritmos
*Aditya Bhargava*

Um guia ilustrado que explica busca binária, recursão, grafos e outros algoritmos com desenhos. O jeito mais leve de aprender um assunto que assusta.

→ [Ver na Amazon](https://link.amazon/B03oZkayS)

### Entendendo Estruturas de Dados
*Marcello La Rocca*

O próximo passo: estruturas de dados mais avançadas aplicadas a problemas reais, mostrando quando e por que usar cada uma.

→ [Ver na Amazon](https://link.amazon/B0eFnuqv3)

## Carreira e boas práticas

### O Programador Pragmático
*Andrew Hunt e David Thomas*

Um clássico que atravessa gerações. Ensina a pensar como um profissional: responsabilidade, código fácil de mudar e aprendizado contínuo.

→ [Ver na Amazon](https://link.amazon/B00QHQaQv)

### O Codificador Limpo
*Robert C. Martin*

Sobre profissionalismo: estimativas, prazos, pressão e como dizer não. Leitura obrigatória para quem quer ser levado a sério.

→ [Ver na Amazon](https://link.amazon/B08Gx7D6r)

### Como Ser Um Programador Melhor
*Pete Goodliffe*

Hábitos e atitudes que separam o bom programador do resto, do código em si ao trabalho em equipe.

→ [Ver na Amazon](https://link.amazon/B06ZZTsi9)', 'peach', null, 'LIVROS', '[]'::jsonb, '[]'::jsonb, '2026-09-14T11:00:00Z')
on conflict (slug) do update set category = excluded.category, topic = excluded.topic, title = excluded.title, summary = excluded.summary,
  body_md = excluded.body_md, tone = excluded.tone, video_url = excluded.video_url, keyword = excluded.keyword,
  materials = excluded.materials, chapters = excluded.chapters, updated_at = now();

insert into site_projects (slug, name, type, status, year, stack, summary, url, repo_url, tone, problem, solution, arch, decisions, tradeoffs, readme_md, sort)
values ('jornal-tech', 'O Jornal Tech', 'Produto', 'Em construção', '2026', '.NET 8 · Claude API · Next.js · Supabase', 'Um jornal de tecnologia e IA que se monta sozinho, em português, a cada duas horas.', 'https://jornal.heliofilho.dev', null, 'lilac', 'Acompanhar IA virou trabalho de tempo integral: dezenas de fontes em inglês, muito ruído e pouca curadoria em português. Eu gastava a manhã lendo e ainda perdia o que importava.', 'Um coletor em .NET roda a cada duas horas, lê 9 feeds RSS e manda cada notícia nova para o Claude, que traduz, resume, classifica e diz se aquilo é notícia de verdade. Quando fontes diferentes falam da mesma coisa, a notícia fica em alta. O site só lê a lista pronta.', array['RSS · 9 fontes', 'Coletor .NET (cron 2h)', 'Claude: resumo e prioridade', 'Supabase Postgres', 'jornal.heliofilho.dev']::text[], array['Mesmo Supabase deste site, em tabelas separadas: um banco só pra manter.', 'Worker simples em vez de Clean Architecture: não é um domínio complexo.', 'Uma chamada ao Claude por notícia, com saída JSON validada.', 'O que não é notícia fica gravado como oculto, pra não pagar a classificação de novo.']::text[], array['Em alta por termos em comum erra quando as manchetes são muito diferentes.', 'Feed RSS muda sem aviso e precisa de monitoramento.', 'Atualiza a cada duas horas, não em tempo real.']::text[], '## Como funciona

1. **Coleta.** 9 feeds RSS (OpenAI, Google DeepMind, The Verge, Ars Technica, MIT Technology Review, Simon Willison, GitHub Blog, Tecnoblog e arXiv), olhando as últimas 48 horas. Oferta e cupom são descartados antes de chegar no modelo.
2. **Sem repetição.** Link que já está no banco não é classificado de novo.
3. **Classificação.** O Claude devolve título e resumo em português, categoria, prioridade e se aquilo deve ser descartado.
4. **Em alta.** Notícias de fontes diferentes que compartilham termos relevantes em até 36 horas.
5. **Site.** Next.js lê do Supabase e se atualiza a cada 10 minutos.

## Onde está o código

Dentro do repositório deste site, na pasta `jornal/`: `collector/` (o robô em .NET), `web/` (o jornal) e `supabase/` (as tabelas).

## Próximos passos

- Juntar a mesma notícia vinda de várias fontes num registro só.
- O jogo diário: uma pergunta por dia sobre a edição.', 1)
on conflict (slug) do update set name = excluded.name, type = excluded.type, status = excluded.status, year = excluded.year, stack = excluded.stack,
  summary = excluded.summary, url = excluded.url, repo_url = excluded.repo_url, tone = excluded.tone, problem = excluded.problem,
  solution = excluded.solution, arch = excluded.arch, decisions = excluded.decisions, tradeoffs = excluded.tradeoffs,
  readme_md = excluded.readme_md, sort = excluded.sort;

insert into site_projects (slug, name, type, status, year, stack, summary, url, repo_url, tone, problem, solution, arch, decisions, tradeoffs, readme_md, sort)
values ('heliofilho-dev', 'heliofilho.dev', 'Produto', 'Em construção', '2026', 'Next.js · Supabase · Vercel', 'Este site: projetos, cofre, jornal e newsletter num lugar só.', 'https://heliofilho.dev', null, 'mint', 'Meu conteúdo estava espalhado entre bio do Instagram, Notion, Substack e links soltos. Quem chegava por um vídeo não achava o resto.', 'Um site só, com o cofre de materiais, os projetos com README e diário, a prévia do jornal e a newsletter. O conteúdo fica no Supabase, então dá pra publicar uma página nova sem novo deploy.', array['Next.js (App Router)', 'Supabase Postgres', 'Vercel']::text[], array['Conteúdo em tabelas do Supabase: publicar não exige deploy.', 'Páginas geradas no servidor e atualizadas a cada 5 minutos.', 'Cada item do cofre tem link curto próprio, pronto pra mandar na DM.']::text[], array['Editar markdown direto na tabela é menos confortável que o Notion.']::text[], '', 2)
on conflict (slug) do update set name = excluded.name, type = excluded.type, status = excluded.status, year = excluded.year, stack = excluded.stack,
  summary = excluded.summary, url = excluded.url, repo_url = excluded.repo_url, tone = excluded.tone, problem = excluded.problem,
  solution = excluded.solution, arch = excluded.arch, decisions = excluded.decisions, tradeoffs = excluded.tradeoffs,
  readme_md = excluded.readme_md, sort = excluded.sort;

insert into site_projects (slug, name, type, status, year, stack, summary, url, repo_url, tone, problem, solution, arch, decisions, tradeoffs, readme_md, sort)
values ('cofre', 'Cofre', 'Produto', 'Em construção', '2026', 'Next.js · Supabase', 'Biblioteca aberta com repos, livros, equipamento e uma página por vídeo.', 'https://heliofilho.dev/cofre', null, 'butter', 'Cada vídeo gera comentários pedindo o link do material, e os materiais viviam soltos no Notion.', 'O cofre saiu do Notion e veio pra dentro do site. Cada item tem página própria com link curto, busca e filtro por tipo.', array['Supabase (cofre_items)', 'Next.js', 'heliofilho.dev/cofre/[item]']::text[], array['Cada item guarda uma palavra-chave, pensando na automação de DM.', 'Texto em markdown: dá pra escrever do celular.']::text[], '{}'::text[], '', 3)
on conflict (slug) do update set name = excluded.name, type = excluded.type, status = excluded.status, year = excluded.year, stack = excluded.stack,
  summary = excluded.summary, url = excluded.url, repo_url = excluded.repo_url, tone = excluded.tone, problem = excluded.problem,
  solution = excluded.solution, arch = excluded.arch, decisions = excluded.decisions, tradeoffs = excluded.tradeoffs,
  readme_md = excluded.readme_md, sort = excluded.sort;

insert into site_projects (slug, name, type, status, year, stack, summary, url, repo_url, tone, problem, solution, arch, decisions, tradeoffs, readme_md, sort)
values ('planilio', 'Planilio', 'SaaS', 'No ar', null, '', 'Organize suas finanças e veja como o seu dinheiro vai estar nos próximos 24 meses.', 'https://planilio.com.br', null, 'sky', null, null, '{}'::text[], '{}'::text[], '{}'::text[], '', 4)
on conflict (slug) do update set name = excluded.name, type = excluded.type, status = excluded.status, year = excluded.year, stack = excluded.stack,
  summary = excluded.summary, url = excluded.url, repo_url = excluded.repo_url, tone = excluded.tone, problem = excluded.problem,
  solution = excluded.solution, arch = excluded.arch, decisions = excluded.decisions, tradeoffs = excluded.tradeoffs,
  readme_md = excluded.readme_md, sort = excluded.sort;

insert into site_projects (slug, name, type, status, year, stack, summary, url, repo_url, tone, problem, solution, arch, decisions, tradeoffs, readme_md, sort)
values ('manychat-proprio', 'ManyChat próprio', 'Automação', 'Ideia', null, 'Instagram Messaging API · Webhooks', 'Responder comentários e DMs com o link certo do cofre, sem depender do ManyChat.', null, null, 'peach', 'Cada vídeo gera centenas de comentários pedindo o link do material.', 'Um webhook recebe a palavra-chave do comentário, acha o item do cofre com aquela palavra e responde por DM com o link da página.', array['Instagram', 'Webhook', 'Cofre (palavra-chave)', 'DM com o link']::text[], '{}'::text[], '{}'::text[], '', 5)
on conflict (slug) do update set name = excluded.name, type = excluded.type, status = excluded.status, year = excluded.year, stack = excluded.stack,
  summary = excluded.summary, url = excluded.url, repo_url = excluded.repo_url, tone = excluded.tone, problem = excluded.problem,
  solution = excluded.solution, arch = excluded.arch, decisions = excluded.decisions, tradeoffs = excluded.tradeoffs,
  readme_md = excluded.readme_md, sort = excluded.sort;

insert into site_projects (slug, name, type, status, year, stack, summary, url, repo_url, tone, problem, solution, arch, decisions, tradeoffs, readme_md, sort)
values ('jogo-diario', 'Jogo diário', 'Produto', 'Ideia', null, 'Next.js · Supabase Auth', 'Uma pergunta por dia sobre as notícias do jornal, com ranking semanal.', null, null, 'rose', 'Dar um motivo pra voltar ao jornal todo dia.', 'Uma pergunta por dia gerada a partir das notícias da edição, com login por link mágico e ranking semanal.', '{}'::text[], '{}'::text[], '{}'::text[], '', 6)
on conflict (slug) do update set name = excluded.name, type = excluded.type, status = excluded.status, year = excluded.year, stack = excluded.stack,
  summary = excluded.summary, url = excluded.url, repo_url = excluded.repo_url, tone = excluded.tone, problem = excluded.problem,
  solution = excluded.solution, arch = excluded.arch, decisions = excluded.decisions, tradeoffs = excluded.tradeoffs,
  readme_md = excluded.readme_md, sort = excluded.sort;

insert into project_updates (project_slug, title, body_md, published_at)
select 'heliofilho-dev', 'Novo layout e o cofre dentro do site', 'O site ganhou o layout novo e o cofre saiu do Notion: repos, livros, equipamento e a página de cada vídeo agora moram aqui, cada um com link próprio.', '2026-09-30T12:00:00Z'
where not exists (select 1 from project_updates where project_slug = 'heliofilho-dev' and title = 'Novo layout e o cofre dentro do site');
