// Gera supabase/content.sql (tabelas + RLS + carga inicial) a partir de lib/contentSeed.ts.
// Uso: node scripts/content-sql.mjs > supabase/content.sql
// Node 24 remove os tipos do .ts sozinho. O SQL é idempotente: rodar de novo atualiza as linhas.
import { seedCofre, seedProjects, seedUpdates } from '../lib/contentSeed.ts'

const q = (v) => (v === null || v === undefined ? 'null' : `'${String(v).replaceAll("'", "''")}'`)
const arr = (a) => (a.length ? `array[${a.map(q).join(', ')}]::text[]` : `'{}'::text[]`)
const json = (v) => `${q(JSON.stringify(v))}::jsonb`

const out = []
out.push(`-- Conteúdo do heliofilho.dev: cofre, projetos e diário dos projetos.
-- Gerado por scripts/content-sql.mjs. Rodar no SQL Editor do Supabase (projeto do portfólio).

create table if not exists cofre_items (
  slug text primary key check (slug ~ '^[a-z0-9-]+$'),
  category text not null check (category in ('Vídeos', 'Repos', 'Produtos', 'Livros', 'Guias')),
  topic text,
  title text not null,
  summary text not null,
  body_md text not null default '',
  tone text not null default 'lilac' check (tone in ('lilac', 'mint', 'peach', 'butter', 'sky', 'rose')),
  video_url text,
  keyword text,
  materials jsonb not null default '[]',
  chapters jsonb not null default '[]',
  published boolean not null default true,
  published_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create unique index if not exists cofre_items_keyword on cofre_items (upper(keyword)) where keyword is not null;

create table if not exists site_projects (
  slug text primary key check (slug ~ '^[a-z0-9-]+$'),
  name text not null,
  type text not null,
  status text not null check (status in ('No ar', 'Em construção', 'Ideia')),
  year text,
  stack text not null default '',
  summary text not null,
  url text,
  repo_url text,
  tone text not null default 'lilac' check (tone in ('lilac', 'mint', 'peach', 'butter', 'sky', 'rose')),
  problem text,
  solution text,
  arch text[] not null default '{}',
  decisions text[] not null default '{}',
  tradeoffs text[] not null default '{}',
  readme_md text not null default '',
  sort int not null default 0,
  published boolean not null default true
);

create table if not exists project_updates (
  id bigint generated by default as identity primary key,
  project_slug text not null references site_projects (slug) on update cascade on delete cascade,
  title text not null,
  body_md text not null,
  published_at timestamptz not null default now()
);

alter table cofre_items enable row level security;
alter table site_projects enable row level security;
alter table project_updates enable row level security;

drop policy if exists "cofre publico" on cofre_items;
create policy "cofre publico" on cofre_items for select using (published);
drop policy if exists "projetos publicos" on site_projects;
create policy "projetos publicos" on site_projects for select using (published);
drop policy if exists "diario publico" on project_updates;
create policy "diario publico" on project_updates for select using (true);
`)

for (const c of seedCofre) {
  out.push(`insert into cofre_items (slug, category, topic, title, summary, body_md, tone, video_url, keyword, materials, chapters, published_at)
values (${[q(c.slug), q(c.category), q(c.topic), q(c.title), q(c.summary), q(c.body_md), q(c.tone), q(c.video_url), q(c.keyword), json(c.materials), json(c.chapters), q(c.published_at)].join(', ')})
on conflict (slug) do update set category = excluded.category, topic = excluded.topic, title = excluded.title, summary = excluded.summary,
  body_md = excluded.body_md, tone = excluded.tone, video_url = excluded.video_url, keyword = excluded.keyword,
  materials = excluded.materials, chapters = excluded.chapters, updated_at = now();
`)
}

for (const p of seedProjects) {
  out.push(`insert into site_projects (slug, name, type, status, year, stack, summary, url, repo_url, tone, problem, solution, arch, decisions, tradeoffs, readme_md, sort)
values (${[q(p.slug), q(p.name), q(p.type), q(p.status), q(p.year), q(p.stack), q(p.summary), q(p.url), q(p.repo_url), q(p.tone), q(p.problem), q(p.solution), arr(p.arch), arr(p.decisions), arr(p.tradeoffs), q(p.readme_md), p.sort].join(', ')})
on conflict (slug) do update set name = excluded.name, type = excluded.type, status = excluded.status, year = excluded.year, stack = excluded.stack,
  summary = excluded.summary, url = excluded.url, repo_url = excluded.repo_url, tone = excluded.tone, problem = excluded.problem,
  solution = excluded.solution, arch = excluded.arch, decisions = excluded.decisions, tradeoffs = excluded.tradeoffs,
  readme_md = excluded.readme_md, sort = excluded.sort;
`)
}

for (const u of seedUpdates) {
  out.push(`insert into project_updates (project_slug, title, body_md, published_at)
select ${[q(u.project_slug), q(u.title), q(u.body_md), q(u.published_at)].join(', ')}
where not exists (select 1 from project_updates where project_slug = ${q(u.project_slug)} and title = ${q(u.title)});
`)
}

process.stdout.write(out.join('\n'))
